### ISSUE TITLE
Check files before running

### ISSUE THREAD

**Issue by charlotterich** [broadinstitute/Drop-seq#123]
Feature suggestion for drop-seq_pipeline.sh:
It would be nice if the pipeline script incorporated some basic tests to check paths and files are correct for the metadata etc. It's a little frustrating to wait an hour or so to discover that the script cannot access a folder, or a file is misnamed.

**Comment by alecw** [comment]
Hi @charlotterich ,

This script is intended as an example of the use of the programs, not necessarily as ready for production.  If you want submit a pull request with these changes, we will consider it, but I frankly I have some reluctance to add complexity because it makes for additional things that can go wrong.

-Alec

**Comment by charlotterich** [comment]
Fair enough, 
Thanks for the response
- Charlotte
