### ISSUE TITLE
TagReadWithGeneFunction with Chromosome disagreement

### ISSUE THREAD

**Issue by MonkeySylvia** [broadinstitute/Drop-seq#161]
Hi,
My lab is interested in transposon expression, so I tried to use TagReadWithGeneFunction to tag reads that were aligned to transposons. I have several TEs that across chromosomes, so I created a gtf file that counts them as a same gene but different transcripts. However, `TagReadWithGeneFunction` skipped this annotation because of the 'Chromosome disagreement'.
Is there anyway I can turn off this check point? Thank you!
Sylvia

**Comment by jamesnemesh** [comment]
You can't turn this off.  It's hard to guess exactly what you're doing with your GTF that is causing the error - are you perhaps using the same gene symbol name for the TEs as for the gene?  You'd run into this error when the same gene symbol has multiple chromosome names, so the gene is ambiguous.

Maybe what you want is a second GTF containing only your TEs, and you run TagReadWithGeneFunction and replace any existing tag with the TE tagging as a separate step? This would overwrite any gene annotations for that read with the TE info, but has the advantage of limiting what you're doing quite a bit, so that you can better understand how to modify your GTF.

Perhaps one you get that working on it's own, you can integrate the two GTFs back together without the error.
