### ISSUE TITLE
DigitalExpression seems to be missing my GENE_NAME_TAG

### ISSUE THREAD

**Issue by rosshandler** [broadinstitute/Drop-seq#174]
Dear Drop-seq team,

I am analysing single cell atac-seq data (SNAREseq). I have followed the pipeline provided in the following webpage (https://github.com/chensong611/SNARE_prep). Everything seems to work but I am getting an empty output in the last step of the pipeline where the counts matrix is generated using Digitalexpression command. That is, not a single count is associated with the peak tags I have provided (GENE_NAME_TAG=ZI). I have checked the bam file to see if the file has been properly tagged and everything looks right. I have not been able to figure out what is the problem I am having.

Do you have any idea about what could be happening?

Below is my command line as well as a short view of my bam file:

DigitalExpression I=samplex.single.interval.bam O=peaks.counts.tsv SUMMARY=peaks.count_summary.txt GENE_NAME_TAG=ZI NUM_CORE_BARCODES=10 EDIT_DISTANCE=1  USE_STRAND_INFO=false

samtools view samplex.single.interval.bam | grep "ZI:" | head
D00323:1013:H23FJBCX3:1:1101:10000:10676	147	chr2	131160494	44	10S65M	=	131160494	-65	TAAGAGACAGCTCCTGGTCTCCAAGGAGGCGGTCGCCATGGCAGCGGGATGCGTCTCGACCCACCCGACAGGGTG	<<<<1<<D<<<1HG<<<<<<<<<<<<</<<<<<<<<<<<GC<<<<<<<<<<<<<<<<<//<<1<<<<<<1<<<<0	MC:Z:65M40S	XC:Z:ATCCGTGTACGA	MD:Z:65	RG:Z:A	ZI:Z:Peak_1094	NM:i:0	XM:Z:CCGGCAACA	MQ:i:44	UQ:i:0	AS:i:130

Thanks in advance
Ivan

**Comment by jamesnemesh** [comment]
Hi,

It looks like the protocol is reliant on an old version of our software (V 1.13).  Are you running that old version of the software?  By your arguments (GENE_NAME_TAG instead of GENE_EXON_TAG), you’re using a more recent version of the software.

You probably want to use this release: https://github.com/broadinstitute/Drop-seq/releases/download/v1.13/Drop-seq_tools-1.13.zip <https://github.com/broadinstitute/Drop-seq/releases/download/v1.13/Drop-seq_tools-1.13.zip>

Change your GENE_NAME_TAG argument to GENE_EXON_TAG. Otherwise, I’m not really aware of this process, so it’s probably more reasonable for you to talk to the SnareSeq author about how to run their software appropriately.

-Jim

**Comment by rosshandler** [comment]
Thank you for the quick answer! That solved my problem.

Best,
Ivan
