### ISSUE TITLE
Truncated File Error During Drop-seq_alignment.sh

### ISSUE THREAD

**Issue by yechoi942** [broadinstitute/Drop-seq#193]
Hi,

I am setting up the drop-seq environment for data processing on RedHat platform.
I downloaded the newest version available of Drop-Seq software from McCarroll Lab website and started running the command Drop-seq_alignment.sh, but ran into unexpected problems, and I would greatly appreciate some help resolving this issue.

When the program gets to "PolyATrimmer" step, it outputs a message:
![PolyATrimmer Output](https://user-images.githubusercontent.com/67242363/85235098-5480e100-b3e0-11ea-9f32-14d723fcabcc.png)

I checked with `samtools view [temp_bam_file.bam] > /dev/null` to see if any of the bam files looked strange, and the bam file [unaligned_tagged_trimmed_smart.bam] was found faulty. The image of the output from this command is attached:

![truncated Bam](https://user-images.githubusercontent.com/67242363/85235152-bfcab300-b3e0-11ea-83fb-5fbc0da96b49.png)

I was wondering if the program was suffering from the lack of memory space and checked with both `top` and `free -m` to check the memory space, and it seemed like this was not the issue. Both outputs are attached:

![top msg](https://user-images.githubusercontent.com/67242363/85235196-3667b080-b3e1-11ea-8432-3c19298ae777.png)

![free -m msg](https://user-images.githubusercontent.com/67242363/85235200-3bc4fb00-b3e1-11ea-94c3-8e54f4c9cdfa.png)

Could this issue come from the overloaded CPU while running the program?
Any suggestion will help.
Thanks.

**Comment by alecw** [comment]
Hi @yechoi942 ,

The reason the output file is truncated is because the program had an error and stopped prematurely.  In general, when you get an error like this, the output file will not be valid.

It appears that your input reads are already aligned.  I say this because an unaligned read would not have a CIGAR string.  PolyATrimmer does not expect to trim an aligned BAM file.  Maybe it should handle be able to handle that, but currently it does not.  If the input is an aligned BAM, and the read is trimmed, it does not adjust the CIGAR string appropriately, leading to the error you report.  

Drop-seq_alignment.sh is a script for aligning reads.  It expects the input not to be aligned.  If for some reason you want to re-align reads that are already aligned, you need to remove alignment information first.  You can use [Picard RevertSam](https://gatk.broadinstitute.org/hc/en-us/articles/360036831851-RevertSam-Picard-) to do that.

Regards, Alec

**Comment by yechoi942** [comment]
Thanks, Alec,

The file I was already aligned, and I was able to do RevertSam to get it to more raw form.

Regards,
Yehyun
