### ISSUE TITLE
Cell Barcode and UMI on both read 1 and read2 

### ISSUE THREAD

**Issue by xmeng** [broadinstitute/Drop-seq#221]
Hi,

Thanks for developing this useful tools. I have PE reads with cell barcode and UMI on both read 1 and 2.
I was wondering if I should run cellular tag and molecular tag programs twice on read 1 and read 2, respectively. 
e.g.,
TagBamWithReadSequenceExtended  BASE_RANGE=1-12 BARCODED_READ=1  TAG_NAME=XC  INPUT=unmapped.bam OUTPUT=unaligned_tagged_Cell.bam
TagBamWithReadSequenceExtended  BASE_RANGE=1-12 BARCODED_READ=2  TAG_NAME=XC INPUT=unmapped.bam OUTPUT=unaligned_tagged_Cell.bam

Thanks in advance,
Tom

**Comment by alecw** [comment]
Hi Tom,

I don't understand -- are you reading the same parts of the molecule in both read 1 and read 2? If so, why?  Can you describe the structure of your reads?  

Regards, Alec

**Comment by xmeng** [comment]
Hi Alex,

Thanks for your reply. Yes, I think the experiment is designed to read same parts of the molecule. I have duplex cell barcodes and UMI on both reads.  The structure of the reads is

Read 1 : Cell barcode + UMI1 + sequence 1
Read 2: Cell barcode + UMI2 + sequence 2

Thanks,
Tom

**Comment by alecw** [comment]
Hi Tom,

I'm still not sure I understand.  The fact that you've got 'UMI1' and 'UMI2' implies to me that these are 2 different sequences.  What are you expecting for downstream analysis?  Should the UMI for a read be the concatenation of these 2 sequences?  And what about the cell barcodes?  Am I to understand that this is the same sequence on both ends of the read pair, since you did not number them 1 and 2?  And what do you expect will happen sequence 1 and sequence 2?  Are these to be concatenated for downstream analysis.

Ultimately, after converting the technical sequence into tags, our tools expect a single, non-paired-end read with XC and XM tags containing cellular and molecular indices, and the SEQ and QUAL fields containing the sequence and quality scores of the biological sequence.  How are you expecting your reads to map into this model?

It's likely that our tools won't help you.  TagBamWithReadSequenceExtended doesn't support setting a tag based on a portion of read 1 concatenated with a portion of read 2.  Also, our tools don't support converting a biological sequence that is partly in read 1 and partly in read 2.  

It sounds like you didn't design this structure.  I think you need to talk to whoever did and understand what the intention is.  You might be able to write some custom code to convert your reads into something the Drop-seq tools can handle.

Regards, Alec

**Comment by xmeng** [comment]
Hi Alec,

Thanks for your detailed reply. You are right. I should speak to the person who designed the experiment about the structure and intention of usage. I will get back to you later if I proceed with the Drop-seq pipeline.

Best,
Tom
