### ISSUE TITLE
CLI says "syntax is changing" but new style doesn't work

### ISSUE THREAD

**Issue by jamestwebber** [broadinstitute/Drop-seq#241]
### Affected tool(s)
I believe this affects all the tools, but I haven't verified exhaustively.

### Affected version(s)
- [x] Latest public release version, 2.4.0

### Description 
The dropseq tools output a warning about Picard's new syntax, but if you try to use that syntax (for instance, to get rid of the warning), it fails.

#### Steps to reproduce
Example command line:

```
TrimStartingSequence -I /dev/stdin -O /dev/stdout ...[other options]
```

Will fail on the `-I` argument. The style with `I=/dev/stdin/ O=/dev/stdout` works but prints the warning.

#### Expected behavior
 It would be nice to either support it or remove the message.

#### Actual behavior
It prints out a help message and bails.

**Comment by jamestwebber** [comment]
Hm I just noticed a potential bug in my args that could explain this, will update if it works this time.

**Comment by alecw** [comment]
Hi James,

We use the [Barclay command-line argument parser](https://github.com/broadinstitute/barclay) that was separated from Picard some years ago.  They decided to switch to dash-style arguments, but still support the legacy equal-sign syntax.  For us, switching styles would be a big effort: lots of workflows, code that parses command lines, arguments that contain arguments, etc., etc.  A lot of this is due to the fact that with equal-sign syntax, splitting a string on whitespace keeps argument name and value together.  The warning message is annoying, but I guess I've managed to tune it out.

If you want to switch to the dash syntax, you'll need to look at Barclay and figure out how to switch.  I'm guessing there is a -D option, or maybe a change to the jarfile needed.

Regards, Alec

**Comment by alecw** [comment]
Hi James,

Sorry, my previous message was wrong.  It's the Picard library that decides what parser to use.  Note that we're using an old version of Picard library (2.20.5) from October 2019.  See method useLegacyParser(line 418) of that version of [CommandLineProgram.java](https://github.com/broadinstitute/picard/blob/48f32ef7a4272458dab854b008b05d3da2ccec0c/src/main/java/picard/cmdline/CommandLineProgram.java).  You'll need to figure out a way to set the property or make a properties file findable.

Regards, Alec
