### ISSUE TITLE
unknown error using ConvertTagToReadGroup

### ISSUE THREAD

**Issue by cynthialiu** [broadinstitute/Drop-seq#243]
Hi,

I have tried to run ConvertTagToReadGroup on my dataset. The job seems failed but I do not know what happened. Could you advise me on how to fix it?

Thanks,
Cynthia 

********** The command line looks like this in the new syntax:
**********
**********    ConvertTagToReadGroup -I donor12_markdup_sorted.bam -O donor12added -CELL_BARCODE_TAG XC -CELL_BC_FILE filtered100K_donor12.txt -SAMPLE_NAME donor12
**********

21:00:39.546 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/mnt/mcfiles/cliu/Drop-seq_tools-2.4.0/jar/lib/picard-2.20.5.jar!/com/intel/gkl/native/libgkl_compression.so
[Tue May 04 21:00:39 AEST 2021] ConvertTagToReadGroup INPUT=donor12_markdup_sorted.bam OUTPUT=donor12added CELL_BARCODE_TAG=XC CELL_BC_FILE=filtered100K_donor12.txt SAMPLE_NAME=donor12    READ_MQ=10 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Tue May 04 21:00:39 AEST 2021] Executing as cliu@scn02.svi.edu.au on Linux 3.10.0-1160.15.2.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_282-b08; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.4.0(3d2b3d8_1600201514)
[Tue May 04 21:00:39 AEST 2021] org.broadinstitute.dropseqrna.utils.ConvertTagToReadGroup done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=2058354688
Exception in thread "main" java.lang.NullPointerException
        at org.broadinstitute.dropseqrna.utils.ConvertTagToReadGroup.getReadGroupTemplate(ConvertTagToReadGroup.java:145)
        at org.broadinstitute.dropseqrna.utils.ConvertTagToReadGroup.doWork(ConvertTagToReadGroup.java:92)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at org.broadinstitute.dropseqrna.cmdline.DropSeqMain.main(DropSeqMain.java:42)

**Comment by jamesnemesh** [comment]
Hi,

I have to make a few guesses without being able to see your data:

It looks like the program expects the BAM to have at least one read group, and is failing because there aren’t any. It would definitely be better if the program at least told you this was the problem instead of crashing without any useful information.

Can you add a read group to your BAM via Picard?  See: https://gatk.broadinstitute.org/hc/en-us/articles/360037226472-AddOrReplaceReadGroups-Picard- <https://gatk.broadinstitute.org/hc/en-us/articles/360037226472-AddOrReplaceReadGroups-Picard->

Then try to run again and see if that fixes the problem.

-Jim

**Comment by jamesnemesh** [comment]
It's been a while since we heard from you, I hope the last comment fixed your issue.
