### ISSUE TITLE
About generic reads of barcode

### ISSUE THREAD

**Issue by 10KGenomics** [broadinstitute/Drop-seq#309]
Dear sir:
Hello, sir. I want to know about the calculation of generic reads. In the digitalexpression module, we get a summary. I want to know how to count generic reads and uniq UMI. In the BAM file, each read will show the Mapping to gene name and gene function, but there are often a variety of gene names and gene functions I want to count the sequencing saturation, so I must know the types of all barcode&umi&gene reads numbers ， barcode&umi&gene reads numbers that are detected only once, so as to calculate the saturation？
![image](https://user-images.githubusercontent.com/67781404/174115922-d1097c11-3742-4857-84a2-07f4547a942a.png)
![image](https://user-images.githubusercontent.com/67781404/174117145-7527027e-300c-434d-83e0-fbb71d48b172.png)

**Comment by jamesnemesh** [comment]
Hi,

It sounds like you want to run GatherMolecularBarcodeDistributionByGene.  This has the same set of arguments as DigitalExpression, but instead of producing a matrix of cell x gene UMI counts, it instead produces a long matrix for each cell, gene, UMI sequence, and the number of sequencing reads that uniquely map to it.

```
Cell Barcode	Gene	Molecular_Barcode	Num_Obs
AAACCCAAGAGCAGTC	A2M	CTTATTTCAGGT	1
AAACCCAAGAGCAGTC	A2ML1-AS1	CCTAGTCCCTAC	1
AAACCCAAGAGCAGTC	AAK1	ATATTGTTTTAA	2
AAACCCAAGAGCAGTC	AASDHPPT	GGACGAGTTAAC	1
AAACCCAAGAGCAGTC	AATF	GATCTCACTAAT	1
AAACCCAAGAGCAGTC	ABCB10	ACGGGTCCATTA	1
```
