### ISSUE TITLE
ConvertToRefFlat: Unrecognized VM option 'UseParallelOldGC'

### ISSUE THREAD

**Issue by Rohit-Satyam** [broadinstitute/Drop-seq#352]
Downloaded the latest version of Drop-Seq tools and was trying to make reflat file for my organism but I get this error. I also tried the conda version but the error persists. Kindly help

```
/data/kafsack/tools/Drop-seq_tools-2.5.4/ConvertToRefFlat ANNOTATIONS_FILE=resources/PlasmoDB-64_Pfalciparum3D7.gtf SEQUENCE_DICTIONARY=resources/PlasmoDB-64_Pfalciparum3D7_Genome.dict OUTPUT=resources/PlasmoDB-64_Pfalciparum3D7.refFlat
Unrecognized VM option 'UseParallelOldGC'
Did you mean '(+/-)UseParallelGC'? Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by Rohit-Satyam** [comment]
Solved this issue by installing Java version 8 as follows and dropseq_tools(optional)

```
mamba create -n snakemake -c conda-forge -c bioconda -c cyclus java-jdk dropseq_tools
```

**Comment by mschilli87** [comment]
This is not a real fix. [Picard switched to Java 17 more than a year ago](https://github.com/broadinstitute/picard/releases/tag/3.0.0). Having to maintain two versions of Java and calling a different one depending on the steps of the pipeline is a real pain point. Especially since one tool heavily relies on the other and both come from @broadinstitute (I know, that is true for > 1 K repositories on GH, but I hope my point is clear).

Are there any plans to remedy this by releasing a version on the Drop-seq tools that are compatible with Java 17 (or 21, given that 17 is EOL this year)?

**Comment by mschilli87** [comment]
Just a quick update for anyone else running into this: Java 11 appears to be 'old enough' to run `ConvertToRefFlat`.

**Comment by jamesnemesh** [comment]
Just FYI: We depend on Picard's API for both DropSeq tools and we also use their command line tools.  

We're moving our entire toolkit to Java 21 - we had to rework the entire build and how we handle dependencies to do so.  That may come out as soon as today if I can finish release notes.
