### ISSUE TITLE
DigitalExpression with multiple targets

### ISSUE THREAD

**Issue by fbrundu** [broadinstitute/Drop-seq#44]
Hi,
I have single-cell experiment in which 3 rounds of barcoding (8bp each) are used. This brings the number of cell barcodes up to 800k+.
I have a whitelist, composed by all such allowed barcodes. However, if I use it directly in the DigitalExpression tool all the barcodes are used, thus giving me back a sparse matrix with 800k columns (21G) which is composed almost exclusively by zeroes (the number of actual cells is much lower). I would like to use the DigitalExpression tool with more than one target - but in the [documentation](http://mccarrolllab.org/wp-content/uploads/2015/05/Drop-seqAlignmentCookbook_v1.1Aug2015.pdf) it is stated clearly that:

> Y​ou must use one of these options.
> MIN_NUM_GENES_PER_CELL.​DigitalExpression runs a single iteration across all data, and selects cells that have at least this many genes.
> MIN_NUM_TRANSCRIPTS_PER_CELL.​DigitalExpression runs a single iteration across all data, and selects cells that have at least this many transcripts.
> NUM_CORE_BARCODES.​DigitalExpression counts the number of reads per cell barcode (thresholded by READ_MQ), and only includes cells that have at least this number of reads.
> CELL_BC_FILE. ​Instead of iterating over the BAM and discovering what cell barcodes should be used, override this with a specific subset of cell barcodes in a text file. This file has no header and a single column, containing one cell barcode per line. Since this option doesn’t have to iterate through the BAM to select barcodes, DGE extraction is significantly faster when using this option.

Is it already possible to select both with CELL_BC_FILE and MIN_NUM_GENES_PER_CELL, is it planned or not?

Thanks

**Comment by jamesnemesh** [comment]
In order to do that, you’d need to compute the number of genes per cell barcode that are expressed (IE: compute expression across all reads for each cell, so you can’t “short cut” that), then go back and internally run DGE a second time and extract that subset of cell barcodes that have sufficient numbers of genes.

We don’t plan on supporting this directly, but what you can do is run DGE once using your list of cell barcodes and only look (and output) the summary file (which is quite small by comparison)

CELL_BARCODE	NUM_GENIC_READS	NUM_TRANSCRIPTS	NUM_GENES
GATCGATAGAAACCAT	294884	61105	8558
GGATTACTCATTATCC	281838	60221	8315
TCGAGGCTCAGCCTAA	243163	51186	7215

Then filter on this list to the subset of cell barcodes that have the number of genes you want, and re-run DGE using that cell barcode list. Aside from the manual step (which you can automate pretty easily), it will take roughly the same amount of time it would take to run DGE twice internally.

-Jim

**Comment by fbrundu** [comment]
Perfect, thanks.
