### ISSUE TITLE
Is there a way for NUM_CORE_BARCODES in DigitalExpression to include all barcodes?

### ISSUE THREAD

**Issue by jolespin** [broadinstitute/Drop-seq#71]
Is there an option like NUM_CORE_BARCODES=-1 to include all barcodes? I want to do some post filtering stats in Python but I'm not sure how many barcodes there were in total to put the appropriate number here. 

Thanks!

**Comment by jamesnemesh** [comment]
At a cell barcode length of 12 there are only 4^12 possible barcodes…so you could set it to 17,000,000 iff you wanted, or 2,147,483,647.

-Jim

**Comment by jolespin** [comment]
Haha, yea I guess I didn't think of the total amount possible.  I can see why that parameter is there now.  I will experiment with some different values.  What range of values do usually select for this when visualizing the cumulative distribution effectively?

**Comment by jamesnemesh** [comment]
You generally know the number of beads in the experiment, so that’s a good place to start.

What I might do instead is use the argument MIN_NUM_TRANSCRIPTS_PER_CELL=20.   That’ll pull all cell barcodes that have <X> number of transcripts, then generate DGE for all those cell barcodes.  You can even set that value to 1 if you wish to be exhaustive.

-Jim

**Comment by jolespin** [comment]
Thanks that should do everything I need to do.  Looking forward to getting the data from all of this to analyze : )
