### ISSUE TITLE
Output file of BamTagHistogram

### ISSUE THREAD

**Issue by jwdy** [broadinstitute/Drop-seq#95]
Hi,
  I am using Drop-seq tools 2.1.0 and I am confused  when I get the output file of BamTagHistogram.
  The number of cell barcodes in my results file of BamTagHistogram is more than 100,000,while the number of my sequencing cells is about 10,000. Is this situation normal? And what are the possible reasons?
   Thank you!

**Comment by jamesnemesh** [comment]
There’s 2 things going on here:

1) When you do dropseq, not every bead (which has it’s own cell barcode) gets a cell.  In fact, in the standard protocol, it’s something like 1 in every 10, so that two cells will rarely be encapsulated with a single bead.  Those beads still go through the process, and pick up ambient RNA in your cell mixture, and get reads.  This is a large source of those “extra” barcodes.

2)  Every time there’s a sequencing error or PCR error, you can generate a “new” barcode from an existing barcode. Let’s say your cell barcode is AAAAA.  If you have a sequencing error at the first base, you could generate CAAAA, GAAAA, TAAAA.  Multiply that by the number of bases in your barcodes.  Note that your actual cell barcodes usually have far more reads than a PCR error does, which is how the cumulative distribution plot (you made one of those, right?) works.

-Jim

**Comment by jwdy** [comment]
Hi James,
     Thank you very much for your reply. 
     The explanations above are clear and useful.
